### ISSUE TITLE
XML Parsing Error

### ISSUE THREAD

**Issue by valmoxium** [erintheunready/ComicControl#25]
Hi, I've been running into an error after I recently installed ComicCTRL. For some reason the RSS page gives me this error:

![error](https://user-images.githubusercontent.com/6650174/176762930-796ed1ed-f280-48a4-8b9d-40699b1ff50d.jpg)

**XML Parsing Error: junk after document element
Location: https://mnemoria.com/comic/rss
Line Number 2, Column 1:
<b>Deprecated</b>:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in <b>/home/mnemoria/public_html/comiccontrol/parts/comic-rss.php</b> on line <b>7</b><br />
^**

Should I just follow the advice given for the error? I'm not sure how to fix this.

**Comment by pennro-se** [comment]
Hello,

It would seem your PHP version is newer than the one used when creating ComicControl, causing it to spit out a warning that then causes your XML parser to stumble.

The issue is with [lines 7-9 of `/comiccontrol/parts/comic-rss.php`](https://github.com/erintheunready/ComicControl/blob/935724ce894d8c47ba818527a34964906bc166db/comiccontrol/parts/comic-rss.php#L7). I believe a less warning inducing replacement would be as follows:

```php
$s = "";
if ($_SERVER["https"] === "on") {
	$s = "s";
}
```

I do not know when ComicControl will next update, but if you are keen you could replace the problem lines with that above in your ComicControl install.

**Comment by valmoxium** [comment]
Thanks, this worked perfectly. Hopefully there'll be another CC update in the future!
