### ISSUE TITLE
[BUG] PHP Version update breaks Archive page

### ISSUE THREAD

**Issue by piruumi** [erintheunready/ComicControl#38]
Hello, 
I tried emailing your emails, but they are all broken. 
IDK the lingo for this, I made a github just so I can report this bug.

After my PHP version was updated on my domains, the archive pages stopped working. They just show the drop-down menu, and the top bar for comic control is missing. 

When reverting my PHP version to 7.4, it seems to have fixed the issue. PHP version 8.0 and higher seems to cause the archives page to stop working. I have temporarily fixed the issue by revering my PHP versions but I thought I would let you know.  

Everything else appears to be working fine.

**Comment by mrencyc** [comment]
Firstly, I fear Erin is no longer actively working on this project in any capacity, my own attempts to contact her over the last few months have failed just like yours.

However, I also had an issue with the archive page that sounds very similar to yours. [I dug into it and found a missing variable in a SQL call.](https://github.com/mrencyc/ComicControl/commit/1b9d996df500c807a31bc57e74b977038db0674d) Adding that fixed my problem, but I have no idea if it would fix yours, nor can I explain why moving from 7.4 to 8.0 would cause this problem, since I was running 7.4 at the time.

**Comment by piruumi** [comment]
> Firstly, I fear Erin is no longer actively working on this project in any capacity, my own attempts to contact her over the last few months have failed just like yours.
> 
> However, I also had an issue with the archive page that sounds very similar to yours. [I dug into it and found a missing variable in a SQL call.](https://github.com/mrencyc/ComicControl/commit/1b9d996df500c807a31bc57e74b977038db0674d) Adding that fixed my problem, but I have no idea if it would fix yours, nor can I explain why moving from 7.4 to 8.0 would cause this problem, since I was running 7.4 at the time.

Oh gosh! This worked! Thank you so much! I can update my site to 8.1 php now. Thank you again!
